= As an Tenant; Configuring a tenant

== Customer Brief

You work for Red Hat as a Middleware Consultant. Your team has started to work on an IoT use case have raised following JIRA tickets.

*CONFIGURE IOT PROJECT; link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/evaluating_amq_online_on_openshift_container_platform/index#iot-creating-project-messaging[docs]*

    AS A messaging administrator
    I WANT TO configure an IoTProject to use a 'managedStrategy'
    SO THAT my team has the ability to produce/consume messages against the AMQ Cluster via MQTT and HTTP

*REGISTER TEST DEVICE WITH REGISTRY; link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/evaluating_amq_online_on_openshift_container_platform/index#iot-creating-device-messaging[docs]*

    AS A messaging administrator
    I WANT TO register a device
    SO THAT i can associate a credential with the device

*CREATE CREDENTIAL FOR TEST DEVICE; link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/evaluating_amq_online_on_openshift_container_platform/index#iot-creating-device-messaging[docs]*

    AS A messaging administrator
    I WANT TO create a credential
    SO THAT only allowed users can produce messages regarding that device

*CONNECT CONSUMER TO HONO ENDPOINT; link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/evaluating_amq_online_on_openshift_container_platform/index#iot-telemetry-messaging[docs]*

    AS A messaging administrator
    I WANT TO
    SO THAT

*PRODUCE MESSAGES TO MQTT AND HTTP ADAPTERS; link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/evaluating_amq_online_on_openshift_container_platform/index#sending_telemetry_data[docs]*

    AS A messaging administrator
    I WANT TO produce messages via mqtt and http
    SO THAT i know the IoTProject works correctly

== How do I do that?

A starting point for link:templates[YAML templates] has been provided but some have missing properties.
Follow the docs provided and update the YAML. You should reference the AMQ Online download examples for what properties
should be added. Once you have applied the YAML to the cluster, you should see something like:

[source,bash,prettyprint]
----
$ oc apply -n $OPERATOR_NS
iotproject.iot.enmasse.io/iot created
messaginguser.user.enmasse.io/iot.truck1 created

$ oc get pods -n $OPERATOR_NS
enmasse-operator-85f495fc7c-fzq8t           1/1     Running   0          90m
address-space-controller-779b646cb9-cqs5p   1/1     Running   0          90m
api-server-9fc7bf698-4btgd                  1/1     Running   0          90m
user-api-server-556d984467-27xsd            1/1     Running   0          90m
standard-authservice-77859d9ccb-2grlg       1/1     Running   0          53m
qdrouterd-bgfj9fsa0q-0                      1/1     Running   0          37m
admin.bgfj9fsa0q-d867b4bb-clkvg             2/2     Running   0          37m
broker-bgfj9fsa0q-zo09-0                    1/1     Running   0          36m
broker-bgfj9fsa0q-feen-0                    1/1     Running   0          36m
broker-bgfj9fsa0q-qce8-0                    1/1     Running   0          36m
console-5657c8797-drvtp                     2/2     Running   0          36m
qdrouterd-bgfj9fsa0q-1                      1/1     Running   0          35m
qdrouterd-bgfj9fsa0q-2                      1/1     Running   0          34m
iot-operator-564dc665b9-hlzxl               1/1     Running   0          18m
iot-auth-service-756888b899-nm5n2           1/1     Running   0          14m
iot-gc-64df47fb7f-p2n5p                     1/1     Running   0          14m
iot-tenant-service-7b868d7956-jqpb2         1/1     Running   0          14m
iot-mqtt-adapter-5957679c77-lfg5s           3/3     Running   0          14m
iot-http-adapter-64996d6f8b-b4mbd           3/3     Running   0          14m
iot-device-registry-b7ff684df-wrd7w         1/1     Running   0          14m
qdrouterd-8jqoi7by7d-0                      1/1     Running   0          2m3s
admin.8jqoi7by7d-6bd5586486-8vz24           2/2     Running   0          2m3s
broker-8jqoi7by7d-6zrr-0                    1/1     Running   0          110s
qdrouterd-8jqoi7by7d-1                      1/1     Running   0          48s

$ oc get svc -n $OPERATOR_NS
NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                   AGE
service/broker-8jqoi7by7d-6zrr           ClusterIP   None             <none>        8080/TCP                                                  111s
service/broker-bgfj9fsa0q-feen           ClusterIP   None             <none>        8080/TCP                                                  36m
service/broker-bgfj9fsa0q-qce8           ClusterIP   None             <none>        8080/TCP                                                  36m
service/broker-bgfj9fsa0q-zo09           ClusterIP   None             <none>        8080/TCP                                                  36m
service/console                          ClusterIP   172.30.232.192   <none>        8443/TCP                                                  89m
service/console-8jqoi7by7d               ClusterIP   172.30.255.247   <none>        8081/TCP                                                  2m4s
service/console-bgfj9fsa0q               ClusterIP   172.30.73.204    <none>        8081/TCP                                                  37m
service/iot-auth-service                 ClusterIP   172.30.150.187   <none>        5671/TCP                                                  14m
service/iot-device-registry              ClusterIP   172.30.190.98    <none>        5671/TCP,8443/TCP                                         14m
service/iot-http-adapter                 ClusterIP   172.30.194.207   <none>        8443/TCP                                                  14m
service/iot-mqtt-adapter                 ClusterIP   172.30.193.202   <none>        8883/TCP                                                  14m
service/iot-tenant-service               ClusterIP   172.30.84.12     <none>        5671/TCP                                                  14m
service/messaging-8jqoi7by7d             ClusterIP   172.30.198.150   <none>        5672/TCP,5671/TCP,55671/TCP,56671/TCP,55672/TCP,443/TCP   2m4s
service/messaging-bgfj9fsa0q             ClusterIP   172.30.185.240   <none>        5672/TCP,5671/TCP,55671/TCP,56671/TCP,55672/TCP,443/TCP   37m
service/qdrouterd-headless-8jqoi7by7d    ClusterIP   None             <none>        55672/TCP,8080/TCP                                        2m4s
service/qdrouterd-headless-bgfj9fsa0q    ClusterIP   None             <none>        55672/TCP,8080/TCP                                        37m
service/queue-scheduler-8jqoi7by7d       ClusterIP   172.30.144.244   <none>        5672/TCP                                                  2m4s
service/queue-scheduler-bgfj9fsa0q       ClusterIP   172.30.43.217    <none>        5672/TCP                                                  37m
service/ragent-8jqoi7by7d                ClusterIP   172.30.175.233   <none>        5671/TCP                                                  2m4s
service/ragent-bgfj9fsa0q                ClusterIP   172.30.135.155   <none>        5671/TCP                                                  37m
service/standard-authservice             ClusterIP   172.30.147.210   <none>        8443/TCP,5671/TCP                                         53m
service/standard-controller-8jqoi7by7d   ClusterIP   172.30.92.174    <none>        8080/TCP                                                  2m4s
service/standard-controller-bgfj9fsa0q   ClusterIP   172.30.207.76    <none>        8080/TCP                                                  37m
service/v1beta1-enmasse-io               ClusterIP   172.30.195.249   <none>        443/TCP                                                   90m
service/v1beta1-user-enmasse-io          ClusterIP   172.30.34.204    <none>        443/TCP                                                   90m

$ oc get route -n $OPERATOR_NS
NAME                                                HOST/PORT                                                                                             PATH   SERVICES               PORT    TERMINATION        WILDCARD
route.route.openshift.io/console                    console-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                           console                https   reencrypt          None
route.route.openshift.io/console-8jqoi7by7d         console-8jqoi7by7d-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                console-8jqoi7by7d     https   reencrypt          None
route.route.openshift.io/console-bgfj9fsa0q         console-bgfj9fsa0q-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                console-bgfj9fsa0q     https   reencrypt          None
route.route.openshift.io/device-registry            device-registry-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                   iot-device-registry    https   reencrypt/None     None
route.route.openshift.io/iot-http-adapter           iot-http-adapter-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                  iot-http-adapter       https   passthrough/None   None
route.route.openshift.io/iot-mqtt-adapter           iot-mqtt-adapter-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com                  iot-mqtt-adapter       mqtts   passthrough/None   None
route.route.openshift.io/messaging-8jqoi7by7d       messaging-8jqoi7by7d-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com              messaging-8jqoi7by7d   amqps   passthrough        None
route.route.openshift.io/messaging-bgfj9fsa0q       messaging-bgfj9fsa0q-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com              messaging-bgfj9fsa0q   amqps   passthrough        None
route.route.openshift.io/messaging-wss-8jqoi7by7d   messaging-wss-8jqoi7by7d-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com          messaging-8jqoi7by7d   https   reencrypt          None
route.route.openshift.io/messaging-wss-bgfj9fsa0q   messaging-wss-bgfj9fsa0q-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com          messaging-bgfj9fsa0q   https   reencrypt          None
route.route.openshift.io/standard-authservice       standard-authservice-openshift-operators.apps.cluster-none-4fd7.none-4fd7.openshiftworkshop.com              standard-authservice   https   reencrypt          None
----

== Whats next?

You've now completed the scenario; well done! If you are interested in extending the scenarios, we suggest looking into:

- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/using_amq_online_on_openshift_container_platform/index#con-brokered-address-space-messaging[Deploy a brokered] AddressSpacePlan and AddressSpace
- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_online_on_openshift_container_platform/managing-address-spaces-messaging#ref-address-space-example-exporting-endpoints-messaging[Export the config] as a ConfigMap which can be used by your client pod
- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_online_on_openshift_container_platform/managing-address-spaces-messaging#ref-address-space-example-exposing-endpoints-messaging[Change how the messaging route is exposed] to use a fixed name, instead of using an auto-generated value
- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/installing_and_managing_amq_online_on_openshift_container_platform/configuring-messaging#con-authentication-services-messaging[Configure the AuthenticationService] to have persistent storage
- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_online_on_openshift_container_platform/managing-address-spaces-messaging#ref-address-space-example-auth-service-messaging[Deploy a none AuthenticationService] which is used by another AddressSpace
- link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html-single/using_amq_online_on_openshift_container_platform/index#logging-into-console-messaging[Use the console] to create and delete spaces
- link:https://github.com/gpe-mw-training/amq-online-hackfest[Have a go doing the engineering/GPTE] hackthon examples

Once you've done that, go have a beer!